### ISSUE TITLE
Error on IOS platform

### ISSUE THREAD

**Issue by james2006gi** [Shinao/Unity-GPU-Boids#4]
I tried to build this project on IOS platform, but app got frozen after launching.
"Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)"
I got this error, have you ever try it on IOS?

**Comment by Shinao** [comment]
Sorry for the late reply, I do not have any IOS devices and cannot test on them, though I would think it's a problem of compute shader which is not a function available in all devices (like IOS).
